default:
  omim_id: "s70QtrXSRDCaNVWaerCdPg"
  #omim_id: "YnTlekLKSu6SpKlNffHnQQ"
  varvis_target: 'uni-leipzig'
  varvis_user: 'hugapi'
  varvis_password: "\u00a723R\u201c3r/\u0026R"
  hgmd_csv_path: "W:/HUG/04 Klinische Genomik/09 HGMD Download and Analyses/HGMD_Advanced_Substitutions.csv.gz"
  panelapp_tsv_path: "W:/HUG/04 Klinische Genomik/10 Panels/MorbidGenes-Panel/PanelAppResult.tsv"
  sysndd_tsv_path: "W:/HUG/04 Klinische Genomik/10 Panels/MorbidGenes-Panel/SysNDD_Genes.tsv"
